name: audio
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  audio_session: ^0.1.21
  flutter_animate: ^4.5.2
  shared_preferences: ^2.0.15
  http: ^1.2.2
  audioplayers: ^6.1.0

  # firebase_core: ^3.8.0
  # firebase_analytics: ^11.10.0
  # firebase_database: ^10.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/